// API endpoints configuration
export const API_ENDPOINTS = {
  // Auth endpoints
  AUTH: {
    CAPTCHA: '/api/auth/captcha/',
    captchaImage: (id: string) => `/api/auth/captcha/${id}/image/`,
    LOGIN: '/api/auth/login/',
    LOGIN_VERIFY: '/api/auth/login/verify/',
    REGISTER: '/api/auth/register/',
    REGISTER_VERIFY: '/api/auth/register/verify/',
    LOGOUT: '/api/auth/logout/',
    ME: '/api/auth/me/',
    USERS: '/api/auth/users/',
    USERS_EXPORT: '/api/auth/users/export/',
    userById: (id: string | number) => `/api/auth/users/${id}/`,
    assignRolesByUserId: (id: string | number) => `/api/auth/users/${id}/assign-roles/`,
    PERMISSIONS: '/api/auth/permissions/',
    permissionById: (id: string | number) => `/api/auth/permissions/${id}/`,
    ROLES: '/api/auth/roles/',
    roleById: (id: string | number) => `/api/auth/roles/${id}/`,
    assignPermissionsByRoleId: (id: string | number) =>
      `/api/auth/roles/${id}/assign-permissions/`,
    REFRESH: '/api/auth/refresh/',
  },
  MEDIA: {
    LIST: '/api/media/',
    byId: (id: string) => `/api/media/${id}/`,
    file: (id: string) => `/api/media/${id}/file/`,
    preview: (id: string) => `/api/media/${id}/preview/`,
  },
  INBOX: {
    LIST: '/api/inbox/',
    byId: (id: string) => `/api/inbox/${id}/`,
    read: (id: string) => `/api/inbox/${id}/read/`,
    READ_ALL: '/api/inbox/read-all/',
    SEND: '/api/inbox/send/',
    UNREAD_COUNT: '/api/inbox/unread-count/',
  },
  SYSTEM: {
    SETTINGS: '/api/system/settings/',
    DIAGNOSTICS: '/api/system/diagnostics/',
    GENERAL: '/api/system/settings/general/',
    SECURITY: '/api/system/settings/security/',
    SMS_PROVIDER: '/api/system/settings/sms-provider/',
    MEDIA: '/api/system/settings/media/',
    DATABASE_BACKUP: '/api/system/settings/database-backup/',
  },
  HEALTH: {
    FULL: '/api/health/',
    LIVE: '/api/health/live/',
    READY: '/api/health/ready/',
  },
  BLOG: {
    POSTS: '/api/blog/posts/',
    postById: (id: string) => `/api/blog/posts/${id}/`,
    postBySlug: (slug: string) => `/api/blog/posts/by-slug/${slug}/`,
    CATEGORIES: '/api/blog/categories/',
    categoryById: (id: string) => `/api/blog/categories/${id}/`,
    COMMENTS: '/api/blog/comments/',
    commentById: (id: string) => `/api/blog/comments/${id}/`,
    commentReply: (id: string) => `/api/blog/comments/${id}/reply/`,
  },
  WALLET: {
    LIST: '/api/wallet/',
    ME: '/api/wallet/me/',
    TRANSACTIONS: '/api/wallet/transactions/',
    byId: (id: string) => `/api/wallet/${id}/`,
    deposit: (id: string) => `/api/wallet/${id}/deposit/`,
    withdraw: (id: string) => `/api/wallet/${id}/withdraw/`,
  },
  PAYMENTS: {
    GATEWAYS: '/api/payments/gateways/',
    DEPOSIT: '/api/payments/deposit/',
    ORDERS: '/api/payments/orders/',
    orderById: (id: string) => `/api/payments/orders/${id}/`,
    callback: (orderId: string, token: string) => `/api/payments/callback/${orderId}/${token}/`,
    ADMIN: {
      SETTINGS: '/api/payments/admin/settings/',
      GATEWAYS: '/api/payments/admin/gateways/',
      gatewayById: (id: string) => `/api/payments/admin/gateways/${id}/`,
      gatewayOrders: (id: string) => `/api/payments/admin/gateways/${id}/orders/`,
      MANUAL_DEPOSIT: '/api/payments/admin/manual-deposit/',
      DRIVERS: '/api/payments/admin/drivers/',
    },
  },
  FINANCE: {
    DASHBOARD: '/api/finance/dashboard/',
    MRR: '/api/finance/mrr/',
    FORECAST: '/api/finance/forecast/',
    REVENUE_BY_PRODUCT: '/api/finance/revenue-by-product/',
    COUPONS_IMPACT: '/api/finance/coupons-impact/',
  },
  CATALOG: {
    PRODUCTS: '/api/catalog/products/',
    productBySlug: (slug: string) => `/api/catalog/products/${slug}/`,
    CATEGORIES: '/api/catalog/categories/',
    categoryBySlug: (slug: string) => `/api/catalog/categories/${slug}/`,
    categoryProducts: (slug: string) => `/api/catalog/categories/${slug}/products/`,
    ADMIN: {
      PRODUCTS: '/api/catalog/admin/products/',
      productById: (id: string) => `/api/catalog/admin/products/${id}/`,
      CATEGORIES: '/api/catalog/admin/categories/',
      categoryById: (id: string) => `/api/catalog/admin/categories/${id}/`,
      releases: (id: string) => `/api/catalog/admin/products/${id}/releases/`,
      publish: (id: string) => `/api/catalog/admin/products/${id}/publish/`,
      unpublish: (id: string) => `/api/catalog/admin/products/${id}/unpublish/`,
      duplicatePlan: (id: string) => `/api/catalog/admin/products/${id}/duplicate-plan/`,
      licensingSecret: (id: string) => `/api/catalog/admin/products/${id}/licensing-secret/`,
    },
  },
  COMMERCE: {
    COUPONS_VALIDATE: '/api/commerce/coupons/validate/',
    ORDERS: '/api/commerce/orders/',
    orderById: (id: string) => `/api/commerce/orders/${id}/`,
    ADMIN: {
      COUPONS: '/api/commerce/admin/coupons/',
      couponById: (id: string) => `/api/commerce/admin/coupons/${id}/`,
      ORDERS: '/api/commerce/admin/orders/',
      ORDERS_EXPORT: '/api/commerce/admin/orders/export/',
      orderById: (id: string) => `/api/commerce/admin/orders/${id}/`,
      BULK_GENERATE_COUPONS: '/api/commerce/admin/coupons/bulk-generate/',
    },
  },
  LICENSING: {
    ACTIVATE: '/api/licensing/activate/',
    HEARTBEAT: '/api/licensing/heartbeat/',
    VALIDATE: '/api/licensing/validate/',
    LICENSES: '/api/licensing/licenses/',
    licenseById: (id: string) => `/api/licensing/licenses/${id}/`,
    deactivate: (id: string) => `/api/licensing/licenses/${id}/deactivate/`,
    revealKey: (id: string) => `/api/licensing/licenses/${id}/reveal-key/`,
    DOWNLOADS: '/api/licensing/downloads/',
    downloadByToken: '/api/licensing/download/',
    ADMIN: {
      INSTALLATIONS: '/api/licensing/admin/installations/',
      LICENSES: '/api/licensing/admin/licenses/',
      licenseById: (id: string) => `/api/licensing/admin/licenses/${id}/`,
    },
  },
  TICKETS: {
    LIST: '/api/tickets/',
    QUEUE: '/api/tickets/queue/',
    SETTINGS: '/api/tickets/settings/',
    TYPES: '/api/tickets/types/',
    typeById: (id: string) => `/api/tickets/types/${id}/`,
    DEPARTMENTS: '/api/tickets/departments/',
    DEPARTMENTS_AVAILABLE: '/api/tickets/departments/available/',
    PERSONAL_ELIGIBILITY: '/api/tickets/personal/eligibility/',
    PERSONAL_RECIPIENTS: '/api/tickets/personal/recipients/',
    departmentById: (id: string) => `/api/tickets/departments/${id}/`,
    departmentRoles: (id: string) => `/api/tickets/departments/${id}/roles/`,
    departmentOperators: (id: string) => `/api/tickets/departments/${id}/operators/`,
    departmentMembers: (id: string) => `/api/tickets/departments/${id}/members/`,
    departmentMemberByUserId: (deptId: string, userId: number | string) =>
      `/api/tickets/departments/${deptId}/members/${userId}/`,
    departmentOperatorByUserId: (deptId: string, userId: number | string) =>
      `/api/tickets/departments/${deptId}/operators/${userId}/`,
    GUEST: '/api/tickets/guest/',
    GUEST_TRACK_REQUEST: '/api/tickets/guest/track/request/',
    GUEST_TRACK_VERIFY: '/api/tickets/guest/track/verify/',
    GUEST_ME: '/api/tickets/guest/me/',
    GUEST_MESSAGES: '/api/tickets/guest/messages/',
    GUEST_CLOSE: '/api/tickets/guest/close/',
    byId: (id: string) => `/api/tickets/${id}/`,
    take: (id: string) => `/api/tickets/${id}/take/`,
    release: (id: string) => `/api/tickets/${id}/release/`,
    refer: (id: string) => `/api/tickets/${id}/refer/`,
    escalate: (id: string) => `/api/tickets/${id}/escalate/`,
    close: (id: string) => `/api/tickets/${id}/close/`,
    messages: (id: string) => `/api/tickets/${id}/messages/`,
    events: (id: string) => `/api/tickets/${id}/events/`,
    attachments: (id: string) => `/api/tickets/${id}/attachments/`,
  },
  SEO: {
    PUBLIC_SETTINGS: '/api/seo/public-settings/',
    SETTINGS: '/api/seo/settings/',
    SITEMAP: '/api/sitemap.xml',
    SITEMAP_PRODUCTS: '/api/sitemap-products.xml',
    SITEMAP_BLOG: '/api/sitemap-blog.xml',
    GSC: {
      STATUS: '/api/seo/gsc/status/',
      CONNECT: '/api/seo/gsc/connect/',
      CALLBACK: '/api/seo/gsc/callback/',
      ANALYTICS: '/api/seo/gsc/analytics/',
      QUERIES: '/api/seo/gsc/queries/',
      PAGES: '/api/seo/gsc/pages/',
      INDEXING_ISSUES: '/api/seo/gsc/indexing-issues/',
      SUBMIT_SITEMAP: '/api/seo/gsc/submit-sitemap/',
    },
  },
  INTERNAL: {
    REVALIDATE: '/api/internal/revalidate/',
  },
} as const

