// API endpoints configuration
export const API_ENDPOINTS = {
  // Auth endpoints
  AUTH: {
    CAPTCHA: '/api/auth/captcha/',
    LOGIN: '/api/auth/login/',
    LOGIN_VERIFY: '/api/auth/login/verify/',
    LOGIN_RESEND: '/api/auth/login/resend/',
    REGISTER: '/api/auth/register/',
    REGISTER_VERIFY: '/api/auth/register/verify/',
    REGISTER_RESEND: '/api/auth/register/resend/',
    LOGOUT: '/api/auth/logout/',
    ME: '/api/auth/me/',
    USERS: '/api/auth/users/',
    USERS_EXPORT: '/api/auth/users/export/',
    userById: (id: string | number) => `/api/auth/users/${id}/`,
    assignRolesByUserId: (id: string | number) => `/api/auth/users/${id}/assign-roles/`,
    PERMISSIONS: '/api/auth/permissions/',
    ROLES: '/api/auth/roles/',
    roleById: (id: string | number) => `/api/auth/roles/${id}/`,
    REFRESH: '/api/auth/refresh/',
    VERIFY: '/api/auth/verify',
  },
  MEDIA: {
    LIST: '/api/media/',
    byId: (id: string) => `/api/media/${id}/`,
    file: (id: string) => `/api/media/${id}/file/`,
    preview: (id: string) => `/api/media/${id}/preview/`,
  },
  INBOX: {
    LIST: '/api/inbox/',
    byId: (id: string) => `/api/inbox/${id}/`,
    read: (id: string) => `/api/inbox/${id}/read/`,
    READ_ALL: '/api/inbox/read-all/',
    SEND: '/api/inbox/send/',
    UNREAD_COUNT: '/api/inbox/unread-count/',
  },
  SYSTEM: {
    SETTINGS: '/api/system/settings/',
    DIAGNOSTICS: '/api/system/diagnostics/',
    GENERAL: '/api/system/settings/general/',
    SECURITY: '/api/system/settings/security/',
    SMS_PROVIDER: '/api/system/settings/sms-provider/',
    MEDIA: '/api/system/settings/media/',
    DATABASE_BACKUP: '/api/system/settings/database-backup/',
  },
  HEALTH: {
    FULL: '/api/health/',
    LIVE: '/api/health/live/',
    READY: '/api/health/ready/',
  },
  BLOG: {
    POSTS: '/api/blog/posts/',
    postById: (id: string) => `/api/blog/posts/${id}/`,
    CATEGORIES: '/api/blog/categories/',
    categoryById: (id: string) => `/api/blog/categories/${id}/`,
    COMMENTS: '/api/blog/comments/',
    commentById: (id: string) => `/api/blog/comments/${id}/`,
    commentReply: (id: string) => `/api/blog/comments/${id}/reply/`,
  },
  WALLET: {
    LIST: '/api/wallet/',
    ME: '/api/wallet/me/',
    TRANSACTIONS: '/api/wallet/transactions/',
    byId: (id: string) => `/api/wallet/${id}/`,
    deposit: (id: string) => `/api/wallet/${id}/deposit/`,
    withdraw: (id: string) => `/api/wallet/${id}/withdraw/`,
  },
  PAYMENTS: {
    GATEWAYS: '/api/payments/gateways/',
    DEPOSIT: '/api/payments/deposit/',
    ORDERS: '/api/payments/orders/',
    orderById: (id: string) => `/api/payments/orders/${id}/`,
    ADMIN: {
      SETTINGS: '/api/payments/admin/settings/',
      GATEWAYS: '/api/payments/admin/gateways/',
      gatewayById: (id: string) => `/api/payments/admin/gateways/${id}/`,
      gatewayOrders: (id: string) => `/api/payments/admin/gateways/${id}/orders/`,
      MANUAL_DEPOSIT: '/api/payments/admin/manual-deposit/',
      DRIVERS: '/api/payments/admin/drivers/',
    },
  },
  FINANCE: {
    MANUAL_PAYMENTS: '/api/finance/manual-payments/',
    MY_SALE_ORDERS: '/api/finance/my-sale-orders/',
    mySaleOrderById: (id: string) => `/api/finance/my-sale-orders/${id}/`,
  },
  CATALOG: {
    PRODUCTS: '/api/catalog/products/',
    productBySlug: (slug: string) => `/api/catalog/products/${slug}/`,
    CATEGORIES: '/api/catalog/categories/',
    categoryBySlug: (slug: string) => `/api/catalog/categories/${slug}/`,
    ADMIN: {
      PRODUCTS: '/api/catalog/admin/products/',
      productById: (id: string) => `/api/catalog/admin/products/${id}/`,
      CATEGORIES: '/api/catalog/admin/categories/',
      releases: (id: string) => `/api/catalog/admin/products/${id}/releases/`,
    },
  },
  COMMERCE: {
    COUPONS_VALIDATE: '/api/commerce/coupons/validate/',
    ORDERS: '/api/commerce/orders/',
    orderById: (id: string) => `/api/commerce/orders/${id}/`,
    ADMIN: {
      COUPONS: '/api/commerce/admin/coupons/',
      couponById: (id: string) => `/api/commerce/admin/coupons/${id}/`,
    },
  },
  LICENSING: {
    LICENSES: '/api/licensing/licenses/',
    licenseById: (id: string) => `/api/licensing/licenses/${id}/`,
    deactivate: (id: string) => `/api/licensing/licenses/${id}/deactivate/`,
    revealKey: (id: string) => `/api/licensing/licenses/${id}/reveal-key/`,
    DOWNLOADS: '/api/licensing/downloads/',
    ADMIN: {
      INSTALLATIONS: '/api/licensing/admin/installations/',
    },
  },
  TICKETS: {
    LIST: '/api/tickets/',
    QUEUE: '/api/tickets/queue/',
    SETTINGS: '/api/tickets/settings/',
    TYPES: '/api/tickets/types/',
    typeById: (id: string) => `/api/tickets/types/${id}/`,
    DEPARTMENTS: '/api/tickets/departments/',
    DEPARTMENTS_AVAILABLE: '/api/tickets/departments/available/',
    PERSONAL_ELIGIBILITY: '/api/tickets/personal/eligibility/',
    PERSONAL_RECIPIENTS: '/api/tickets/personal/recipients/',
    departmentById: (id: string) => `/api/tickets/departments/${id}/`,
    departmentRoles: (id: string) => `/api/tickets/departments/${id}/roles/`,
    departmentOperators: (id: string) => `/api/tickets/departments/${id}/operators/`,
    departmentMembers: (id: string) => `/api/tickets/departments/${id}/members/`,
    departmentMemberByUserId: (deptId: string, userId: number | string) =>
      `/api/tickets/departments/${deptId}/members/${userId}/`,
    departmentOperatorByUserId: (deptId: string, userId: number | string) =>
      `/api/tickets/departments/${deptId}/operators/${userId}/`,
    GUEST: '/api/tickets/guest/',
    GUEST_TRACK_REQUEST: '/api/tickets/guest/track/request/',
    GUEST_TRACK_VERIFY: '/api/tickets/guest/track/verify/',
    GUEST_ME: '/api/tickets/guest/me/',
    GUEST_MESSAGES: '/api/tickets/guest/messages/',
    GUEST_CLOSE: '/api/tickets/guest/close/',
    byId: (id: string) => `/api/tickets/${id}/`,
    take: (id: string) => `/api/tickets/${id}/take/`,
    release: (id: string) => `/api/tickets/${id}/release/`,
    refer: (id: string) => `/api/tickets/${id}/refer/`,
    escalate: (id: string) => `/api/tickets/${id}/escalate/`,
    close: (id: string) => `/api/tickets/${id}/close/`,
    messages: (id: string) => `/api/tickets/${id}/messages/`,
    events: (id: string) => `/api/tickets/${id}/events/`,
    attachments: (id: string) => `/api/tickets/${id}/attachments/`,
  },
} as const

